//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.7.3081.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class game {
    
    private gameScript[] scriptsField;
    
    private gameEvent[] eventsField;
    
    private gameSound[] soundsField;
    
    private gameFont[] fontsField;
    
    private gameSymbol[] symbolsField;
    
    private gameProxygen proxygenField;
    
    private gamePhase[] phasesField;
    
    private gameDocument[] documentsField;
    
    private gameGameMode[] gameModesField;
    
    private gameGlobalvariable[] globalvariablesField;
    
    private gameMarker[] markersField;
    
    private gameCard cardField;
    
    private gameGameboards gameboardsField;
    
    private table tableField;
    
    private gamePlayer playerField;
    
    private gameShared sharedField;
    
    private deckSection[] deckField;
    
    private deckSection[] sharedDeckField;
    
    private string idField;
    
    private string nameField;
    
    private string versionField;
    
    private string octgnVersionField;
    
    private string scriptVersionField;
    
    private string markersizeField;
    
    private boolean cardsRevertToOriginalOnGroupChangeField;
    
    private bool cardsRevertToOriginalOnGroupChangeFieldSpecified;
    
    private string setsurlField;
    
    private string gameurlField;
    
    private string authorsField;
    
    private string descriptionField;
    
    private string tagsField;
    
    private string iconurlField;
    
    private boolean usetwosidedtableField;
    
    private boolean changetwosidedtableField;
    
    private string noteBackgroundColorField;
    
    private string noteForegroundColorField;
    
    public game() {
        this.scriptVersionField = "0.0.0.0";
        this.markersizeField = "25";
        this.usetwosidedtableField = boolean.True;
        this.changetwosidedtableField = boolean.True;
        this.noteBackgroundColorField = "#FFEBE8C5";
        this.noteForegroundColorField = "#FF000000";
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlArrayItemAttribute("script", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
    public gameScript[] scripts {
        get {
            return this.scriptsField;
        }
        set {
            this.scriptsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlArrayItemAttribute("event", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
    public gameEvent[] events {
        get {
            return this.eventsField;
        }
        set {
            this.eventsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlArrayItemAttribute("sound", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
    public gameSound[] sounds {
        get {
            return this.soundsField;
        }
        set {
            this.soundsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlArrayItemAttribute("font", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
    public gameFont[] fonts {
        get {
            return this.fontsField;
        }
        set {
            this.fontsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlArrayItemAttribute("symbol", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
    public gameSymbol[] symbols {
        get {
            return this.symbolsField;
        }
        set {
            this.symbolsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public gameProxygen proxygen {
        get {
            return this.proxygenField;
        }
        set {
            this.proxygenField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlArrayItemAttribute("phase", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
    public gamePhase[] phases {
        get {
            return this.phasesField;
        }
        set {
            this.phasesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlArrayItemAttribute("document", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
    public gameDocument[] documents {
        get {
            return this.documentsField;
        }
        set {
            this.documentsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlArrayItemAttribute("gameMode", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
    public gameGameMode[] gameModes {
        get {
            return this.gameModesField;
        }
        set {
            this.gameModesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlArrayItemAttribute("globalvariable", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
    public gameGlobalvariable[] globalvariables {
        get {
            return this.globalvariablesField;
        }
        set {
            this.globalvariablesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlArrayItemAttribute("marker", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
    public gameMarker[] markers {
        get {
            return this.markersField;
        }
        set {
            this.markersField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public gameCard card {
        get {
            return this.cardField;
        }
        set {
            this.cardField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public gameGameboards gameboards {
        get {
            return this.gameboardsField;
        }
        set {
            this.gameboardsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public table table {
        get {
            return this.tableField;
        }
        set {
            this.tableField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public gamePlayer player {
        get {
            return this.playerField;
        }
        set {
            this.playerField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public gameShared shared {
        get {
            return this.sharedField;
        }
        set {
            this.sharedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlArrayItemAttribute("section", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
    public deckSection[] deck {
        get {
            return this.deckField;
        }
        set {
            this.deckField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlArrayItemAttribute("section", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
    public deckSection[] sharedDeck {
        get {
            return this.sharedDeckField;
        }
        set {
            this.sharedDeckField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string version {
        get {
            return this.versionField;
        }
        set {
            this.versionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string octgnVersion {
        get {
            return this.octgnVersionField;
        }
        set {
            this.octgnVersionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute("0.0.0.0")]
    public string scriptVersion {
        get {
            return this.scriptVersionField;
        }
        set {
            this.scriptVersionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    [System.ComponentModel.DefaultValueAttribute("25")]
    public string markersize {
        get {
            return this.markersizeField;
        }
        set {
            this.markersizeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public boolean cardsRevertToOriginalOnGroupChange {
        get {
            return this.cardsRevertToOriginalOnGroupChangeField;
        }
        set {
            this.cardsRevertToOriginalOnGroupChangeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool cardsRevertToOriginalOnGroupChangeSpecified {
        get {
            return this.cardsRevertToOriginalOnGroupChangeFieldSpecified;
        }
        set {
            this.cardsRevertToOriginalOnGroupChangeFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string setsurl {
        get {
            return this.setsurlField;
        }
        set {
            this.setsurlField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string gameurl {
        get {
            return this.gameurlField;
        }
        set {
            this.gameurlField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string authors {
        get {
            return this.authorsField;
        }
        set {
            this.authorsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string description {
        get {
            return this.descriptionField;
        }
        set {
            this.descriptionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string tags {
        get {
            return this.tagsField;
        }
        set {
            this.tagsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string iconurl {
        get {
            return this.iconurlField;
        }
        set {
            this.iconurlField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(boolean.True)]
    public boolean usetwosidedtable {
        get {
            return this.usetwosidedtableField;
        }
        set {
            this.usetwosidedtableField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(boolean.True)]
    public boolean changetwosidedtable {
        get {
            return this.changetwosidedtableField;
        }
        set {
            this.changetwosidedtableField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute("#FFEBE8C5")]
    public string noteBackgroundColor {
        get {
            return this.noteBackgroundColorField;
        }
        set {
            this.noteBackgroundColorField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute("#FF000000")]
    public string noteForegroundColor {
        get {
            return this.noteForegroundColorField;
        }
        set {
            this.noteForegroundColorField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class gameScript {
    
    private string srcField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string src {
        get {
            return this.srcField;
        }
        set {
            this.srcField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class counter {
    
    private string nameField;
    
    private string defaultField;
    
    private boolean resetField;
    
    private string iconField;
    
    public counter() {
        this.defaultField = "0";
        this.resetField = boolean.True;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    [System.ComponentModel.DefaultValueAttribute("0")]
    public string @default {
        get {
            return this.defaultField;
        }
        set {
            this.defaultField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(boolean.True)]
    public boolean reset {
        get {
            return this.resetField;
        }
        set {
            this.resetField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string icon {
        get {
            return this.iconField;
        }
        set {
            this.iconField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
[System.SerializableAttribute()]
public enum boolean {
    
    /// <remarks/>
    True,
    
    /// <remarks/>
    False,
}

/// <remarks/>
[System.Xml.Serialization.XmlIncludeAttribute(typeof(actionSeparator))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(groupActionSeparator))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(cardActionSeparator))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(action))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(groupAction))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(cardAction))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(actionSubmenu))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(cardActionSubmenu))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(groupActionSubmenu))]
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public abstract partial class baseAction {
    
    private string menuField;
    
    private string showIfField;
    
    private string getNameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string menu {
        get {
            return this.menuField;
        }
        set {
            this.menuField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string showIf {
        get {
            return this.showIfField;
        }
        set {
            this.showIfField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string getName {
        get {
            return this.getNameField;
        }
        set {
            this.getNameField = value;
        }
    }
}

/// <remarks/>
[System.Xml.Serialization.XmlIncludeAttribute(typeof(groupActionSeparator))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(cardActionSeparator))]
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class actionSeparator : baseAction {
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class groupActionSeparator : actionSeparator {
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class cardActionSeparator : actionSeparator {
}

/// <remarks/>
[System.Xml.Serialization.XmlIncludeAttribute(typeof(groupAction))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(cardAction))]
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class action : baseAction {
    
    private boolean defaultField;
    
    private string shortcutField;
    
    private string executeField;
    
    private string batchExecuteField;
    
    public action() {
        this.defaultField = boolean.False;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(boolean.False)]
    public boolean @default {
        get {
            return this.defaultField;
        }
        set {
            this.defaultField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string shortcut {
        get {
            return this.shortcutField;
        }
        set {
            this.shortcutField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string execute {
        get {
            return this.executeField;
        }
        set {
            this.executeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string batchExecute {
        get {
            return this.batchExecuteField;
        }
        set {
            this.batchExecuteField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class groupAction : action {
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class cardAction : action {
}

/// <remarks/>
[System.Xml.Serialization.XmlIncludeAttribute(typeof(cardActionSubmenu))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(groupActionSubmenu))]
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class actionSubmenu : baseAction {
    
    private baseAction[] itemsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("cardaction", typeof(cardAction), Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlElementAttribute("cardactions", typeof(cardActionSubmenu), Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlElementAttribute("cardseparator", typeof(cardActionSeparator), Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlElementAttribute("groupaction", typeof(groupAction), Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlElementAttribute("groupactions", typeof(groupActionSubmenu), Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlElementAttribute("groupseparator", typeof(groupActionSeparator), Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public baseAction[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class cardActionSubmenu : actionSubmenu {
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class groupActionSubmenu : actionSubmenu {
}

/// <remarks/>
[System.Xml.Serialization.XmlIncludeAttribute(typeof(table))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(hand))]
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class group {
    
    private baseAction[] itemsField;
    
    private string nameField;
    
    private string iconField;
    
    private groupVisibility visibilityField;
    
    private boolean orderedField;
    
    private string shortcutField;
    
    private boolean movetoField;
    
    private boolean collapsedField;
    
    private groupViewState viewStateField;
    
    public group() {
        this.visibilityField = groupVisibility.none;
        this.orderedField = boolean.True;
        this.movetoField = boolean.True;
        this.collapsedField = boolean.False;
        this.viewStateField = groupViewState.pile;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("cardaction", typeof(cardAction), Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlElementAttribute("cardactions", typeof(cardActionSubmenu), Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlElementAttribute("cardseparator", typeof(cardActionSeparator), Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlElementAttribute("groupaction", typeof(groupAction), Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlElementAttribute("groupactions", typeof(groupActionSubmenu), Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlElementAttribute("groupseparator", typeof(groupActionSeparator), Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public baseAction[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string icon {
        get {
            return this.iconField;
        }
        set {
            this.iconField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(groupVisibility.none)]
    public groupVisibility visibility {
        get {
            return this.visibilityField;
        }
        set {
            this.visibilityField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(boolean.True)]
    public boolean ordered {
        get {
            return this.orderedField;
        }
        set {
            this.orderedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string shortcut {
        get {
            return this.shortcutField;
        }
        set {
            this.shortcutField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(boolean.True)]
    public boolean moveto {
        get {
            return this.movetoField;
        }
        set {
            this.movetoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(boolean.False)]
    public boolean collapsed {
        get {
            return this.collapsedField;
        }
        set {
            this.collapsedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(groupViewState.pile)]
    public groupViewState viewState {
        get {
            return this.viewStateField;
        }
        set {
            this.viewStateField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public enum groupVisibility {
    
    /// <remarks/>
    none,
    
    /// <remarks/>
    me,
    
    /// <remarks/>
    all,
    
    /// <remarks/>
    undefined,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public enum groupViewState {
    
    /// <remarks/>
    collapsed,
    
    /// <remarks/>
    expanded,
    
    /// <remarks/>
    pile,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class table : group {
    
    private string widthField;
    
    private string heightField;
    
    private string backgroundField;
    
    private tableBackgroundStyle backgroundStyleField;
    
    private string boardField;
    
    private string boardPositionField;
    
    public table() {
        this.backgroundStyleField = tableBackgroundStyle.uniform;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string width {
        get {
            return this.widthField;
        }
        set {
            this.widthField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string height {
        get {
            return this.heightField;
        }
        set {
            this.heightField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string background {
        get {
            return this.backgroundField;
        }
        set {
            this.backgroundField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(tableBackgroundStyle.uniform)]
    public tableBackgroundStyle backgroundStyle {
        get {
            return this.backgroundStyleField;
        }
        set {
            this.backgroundStyleField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string board {
        get {
            return this.boardField;
        }
        set {
            this.boardField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string boardPosition {
        get {
            return this.boardPositionField;
        }
        set {
            this.boardPositionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public enum tableBackgroundStyle {
    
    /// <remarks/>
    tile,
    
    /// <remarks/>
    uniform,
    
    /// <remarks/>
    uniformToFill,
    
    /// <remarks/>
    stretch,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class hand : group {
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class gameBoardDef {
    
    private string nameField;
    
    private string widthField;
    
    private string heightField;
    
    private string xField;
    
    private string yField;
    
    private string srcField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string width {
        get {
            return this.widthField;
        }
        set {
            this.widthField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string height {
        get {
            return this.heightField;
        }
        set {
            this.heightField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string x {
        get {
            return this.xField;
        }
        set {
            this.xField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string y {
        get {
            return this.yField;
        }
        set {
            this.yField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string src {
        get {
            return this.srcField;
        }
        set {
            this.srcField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class cardsizeDef {
    
    private string nameField;
    
    private string cornerRadiusField;
    
    private string widthField;
    
    private string heightField;
    
    private string backCornerRadiusField;
    
    private string backWidthField;
    
    private string backHeightField;
    
    private string backField;
    
    private string frontField;
    
    public cardsizeDef() {
        this.cornerRadiusField = "0";
        this.backCornerRadiusField = "-1";
        this.backWidthField = "-1";
        this.backHeightField = "-1";
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    [System.ComponentModel.DefaultValueAttribute("0")]
    public string cornerRadius {
        get {
            return this.cornerRadiusField;
        }
        set {
            this.cornerRadiusField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string width {
        get {
            return this.widthField;
        }
        set {
            this.widthField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string height {
        get {
            return this.heightField;
        }
        set {
            this.heightField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    [System.ComponentModel.DefaultValueAttribute("-1")]
    public string backCornerRadius {
        get {
            return this.backCornerRadiusField;
        }
        set {
            this.backCornerRadiusField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    [System.ComponentModel.DefaultValueAttribute("-1")]
    public string backWidth {
        get {
            return this.backWidthField;
        }
        set {
            this.backWidthField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    [System.ComponentModel.DefaultValueAttribute("-1")]
    public string backHeight {
        get {
            return this.backHeightField;
        }
        set {
            this.backHeightField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string back {
        get {
            return this.backField;
        }
        set {
            this.backField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string front {
        get {
            return this.frontField;
        }
        set {
            this.frontField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class propertyDef {
    
    private string nameField;
    
    private propertyDefType typeField;
    
    private boolean ignoreTextField;
    
    private propertyDefTextKind textKindField;
    
    private boolean hiddenField;
    
    public propertyDef() {
        this.ignoreTextField = boolean.False;
        this.textKindField = propertyDefTextKind.Free;
        this.hiddenField = boolean.False;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public propertyDefType type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(boolean.False)]
    public boolean ignoreText {
        get {
            return this.ignoreTextField;
        }
        set {
            this.ignoreTextField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(propertyDefTextKind.Free)]
    public propertyDefTextKind textKind {
        get {
            return this.textKindField;
        }
        set {
            this.textKindField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(boolean.False)]
    public boolean hidden {
        get {
            return this.hiddenField;
        }
        set {
            this.hiddenField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public enum propertyDefType {
    
    /// <remarks/>
    String,
    
    /// <remarks/>
    Integer,
    
    /// <remarks/>
    Char,
    
    /// <remarks/>
    RichText,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public enum propertyDefTextKind {
    
    /// <remarks/>
    Free,
    
    /// <remarks/>
    Enum,
    
    /// <remarks/>
    Tokens,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class gameEvent {
    
    private string nameField;
    
    private string actionField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string action {
        get {
            return this.actionField;
        }
        set {
            this.actionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class gameSound {
    
    private string nameField;
    
    private string srcField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string src {
        get {
            return this.srcField;
        }
        set {
            this.srcField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class gameFont {
    
    private string srcField;
    
    private string sizeField;
    
    private fonttarget targetField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string src {
        get {
            return this.srcField;
        }
        set {
            this.srcField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string size {
        get {
            return this.sizeField;
        }
        set {
            this.sizeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public fonttarget target {
        get {
            return this.targetField;
        }
        set {
            this.targetField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
[System.SerializableAttribute()]
public enum fonttarget {
    
    /// <remarks/>
    context,
    
    /// <remarks/>
    chat,
    
    /// <remarks/>
    deckeditor,
    
    /// <remarks/>
    notes,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class gameSymbol {
    
    private string nameField;
    
    private string idField;
    
    private string srcField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string src {
        get {
            return this.srcField;
        }
        set {
            this.srcField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class gameProxygen {
    
    private string definitionsrcField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string definitionsrc {
        get {
            return this.definitionsrcField;
        }
        set {
            this.definitionsrcField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class gamePhase {
    
    private string nameField;
    
    private string iconField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string icon {
        get {
            return this.iconField;
        }
        set {
            this.iconField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class gameDocument {
    
    private string srcField;
    
    private string iconField;
    
    private string nameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string src {
        get {
            return this.srcField;
        }
        set {
            this.srcField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string icon {
        get {
            return this.iconField;
        }
        set {
            this.iconField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class gameGameMode {
    
    private string nameField;
    
    private string shortDescriptionField;
    
    private string imageField;
    
    private string playerCountField;
    
    private boolean usetwosidedtableField;
    
    private boolean changetwosidedtableField;
    
    public gameGameMode() {
        this.usetwosidedtableField = boolean.True;
        this.changetwosidedtableField = boolean.True;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string shortDescription {
        get {
            return this.shortDescriptionField;
        }
        set {
            this.shortDescriptionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string image {
        get {
            return this.imageField;
        }
        set {
            this.imageField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string playerCount {
        get {
            return this.playerCountField;
        }
        set {
            this.playerCountField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(boolean.True)]
    public boolean usetwosidedtable {
        get {
            return this.usetwosidedtableField;
        }
        set {
            this.usetwosidedtableField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(boolean.True)]
    public boolean changetwosidedtable {
        get {
            return this.changetwosidedtableField;
        }
        set {
            this.changetwosidedtableField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class gameGlobalvariable {
    
    private string nameField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class gameMarker {
    
    private string srcField;
    
    private string nameField;
    
    private string idField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string src {
        get {
            return this.srcField;
        }
        set {
            this.srcField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class gameCard {
    
    private propertyDef[] propertyField;
    
    private cardsizeDef[] sizeField;
    
    private string nameField;
    
    private string backField;
    
    private string frontField;
    
    private string widthField;
    
    private string heightField;
    
    private string cornerRadiusField;
    
    private string backCornerRadiusField;
    
    private string backWidthField;
    
    private string backHeightField;
    
    public gameCard() {
        this.nameField = "Default";
        this.cornerRadiusField = "0";
        this.backCornerRadiusField = "-1";
        this.backWidthField = "-1";
        this.backHeightField = "-1";
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("property", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public propertyDef[] property {
        get {
            return this.propertyField;
        }
        set {
            this.propertyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("size", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public cardsizeDef[] size {
        get {
            return this.sizeField;
        }
        set {
            this.sizeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute("Default")]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string back {
        get {
            return this.backField;
        }
        set {
            this.backField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string front {
        get {
            return this.frontField;
        }
        set {
            this.frontField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string width {
        get {
            return this.widthField;
        }
        set {
            this.widthField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string height {
        get {
            return this.heightField;
        }
        set {
            this.heightField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    [System.ComponentModel.DefaultValueAttribute("0")]
    public string cornerRadius {
        get {
            return this.cornerRadiusField;
        }
        set {
            this.cornerRadiusField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    [System.ComponentModel.DefaultValueAttribute("-1")]
    public string backCornerRadius {
        get {
            return this.backCornerRadiusField;
        }
        set {
            this.backCornerRadiusField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    [System.ComponentModel.DefaultValueAttribute("-1")]
    public string backWidth {
        get {
            return this.backWidthField;
        }
        set {
            this.backWidthField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    [System.ComponentModel.DefaultValueAttribute("-1")]
    public string backHeight {
        get {
            return this.backHeightField;
        }
        set {
            this.backHeightField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class gameGameboards {
    
    private gameBoardDef[] gameboardField;
    
    private string nameField;
    
    private string srcField;
    
    private string xField;
    
    private string yField;
    
    private string widthField;
    
    private string heightField;
    
    public gameGameboards() {
        this.nameField = "Default";
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("gameboard", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public gameBoardDef[] gameboard {
        get {
            return this.gameboardField;
        }
        set {
            this.gameboardField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute("Default")]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string src {
        get {
            return this.srcField;
        }
        set {
            this.srcField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string x {
        get {
            return this.xField;
        }
        set {
            this.xField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string y {
        get {
            return this.yField;
        }
        set {
            this.yField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string width {
        get {
            return this.widthField;
        }
        set {
            this.widthField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string height {
        get {
            return this.heightField;
        }
        set {
            this.heightField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class gamePlayer {
    
    private object[] itemsField;
    
    private string summaryField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("counter", typeof(counter), Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlElementAttribute("globalvariable", typeof(gamePlayerGlobalvariable), Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlElementAttribute("group", typeof(group), Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlElementAttribute("hand", typeof(hand), Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public object[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string summary {
        get {
            return this.summaryField;
        }
        set {
            this.summaryField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class gamePlayerGlobalvariable {
    
    private string nameField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class gameShared {
    
    private counter[] counterField;
    
    private group[] groupField;
    
    private string summaryField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("counter", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public counter[] counter {
        get {
            return this.counterField;
        }
        set {
            this.counterField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("group", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public group[] group {
        get {
            return this.groupField;
        }
        set {
            this.groupField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string summary {
        get {
            return this.summaryField;
        }
        set {
            this.summaryField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class deckSection {
    
    private string nameField;
    
    private string groupField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string group {
        get {
            return this.groupField;
        }
        set {
            this.groupField = value;
        }
    }
}
