/* 
 * This file was automatically generated by Jesus!
 * Do not modify, or your sins will be regenerated!!
 * XML: C:\Programming\OCTGN\octgnFX\Octgn.Library\Scripting\GameEvents.xml
 *
 * To create the .CS file for this document, 
 * right click the .tt file and click 'Run Custom Tool'
 */
using System;
using System.Collections.Generic;
using System.IO;
using System.Net.Sockets;
using Octgn.Play;

namespace Octgn.Scripting
{
	public class GameEventProxy
	{
	    private readonly Engine engine;
	    
	    public GameEventProxy(Engine scriptEngine)
		{
			engine = scriptEngine;
		}
	
		public void GameStart()
		{
			    
	        if(Program.GameEngine.Definition.Events.ContainsKey("GameStart"))
			{
				foreach(var e in Program.GameEngine.Definition.Events["GameStart"])
				{
					engine.ExecuteFunction(e.PythonFunction);
				}
		  	}
		}

		public void OnLoadDeck(Player player, Group[] groups)
		{
			var args = new object[2];
			args[0] = player;
			args[1] = groups;
	    
	        if(Program.GameEngine.Definition.Events.ContainsKey("OnLoadDeck"))
			{
				foreach(var e in Program.GameEngine.Definition.Events["OnLoadDeck"])
				{
					engine.ExecuteFunction(e.PythonFunction,player, groups);
				}
		  	}
		}

		public void OnChangeCounter(Player player, Counter counter, int newCount)
		{
			var args = new object[3];
			args[0] = player;
			args[1] = counter;
			args[2] = newCount;
	    
	        if(Program.GameEngine.Definition.Events.ContainsKey("OnChangeCounter"))
			{
				foreach(var e in Program.GameEngine.Definition.Events["OnChangeCounter"])
				{
					engine.ExecuteFunction(e.PythonFunction,player, counter, newCount);
				}
		  	}
		}
	}
}
