/* 
 * This file was automatically generated by Jesus!
 * Do not modify, or your sins will be regenerated!!
 * XML: C:\Programming\OCTGN\octgnFX\Octgn.Library\Scripting\GameEvents.xml
 *
 * To create the .CS file for this document, 
 * right click the .tt file and click 'Run Custom Tool'
 */
using System;
using System.Collections.Generic;
using System.IO;
using System.Net.Sockets;

namespace Octgn.Scripting
{
	public class GameEventProxy
	{
	    private readonly Engine engine;
	    
	    public GameEventProxy(Engine scriptEngine)
		{
			engine = scriptEngine;
		}
	
		public void GameStart()
		{
			engine.ExecuteFunction("GameStart");
		}
        // Should be passed a Player and Group[]
        // Then use ScriptApi.GroupConst and ScriptApi.PlayerConst

        // Also needs to search the GameEngine for proper function names
        // to call in the script and call them all
		public void OnLoadDeck(byte player, int[] deck)
		{
			var args = new object[2];
			args[0] = player;
			args[1] = deck;
			engine.ExecuteFunction("OnLoadDeck",player, deck);
		}
	}
}
