//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Octide.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Octide.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap back {
            get {
                object obj = ResourceManager.GetObject("back", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap background {
            get {
                object obj = ResourceManager.GetObject("background", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap blank {
            get {
                object obj = ResourceManager.GetObject("blank", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap deck {
            get {
                object obj = ResourceManager.GetObject("deck", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;game name=&quot;Default Game&quot;
        ///    id=&quot;{GUID}&quot;
        ///    version=&quot;1.0.0.0&quot; 
        ///    tags=&quot;game&quot;
        ///    description=&quot;A base game plugin ready to be customized&quot;
        ///    setsurl=&quot;http://www.octgn.net&quot; 
        ///	gameurl=&quot;http://www.octgn.net&quot;
        ///    authors=&quot;brine&quot;
        ///    iconurl=&quot;https://raw.githubusercontent.com/octgn/OCTGN/master/octgnFX/Octgn/Resources/logolarge.png&quot;
        ///    octgnVersion=&quot;{OCTVER}&quot;
        ///    scriptVersion=&quot;3.1.0.2&quot;
        ///    markersize=&quot;25&quot;
        ///    &gt;
        ///    &lt;scripts&gt;
        ///    &lt;/scripts&gt;
        ///    &lt;events&gt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string definition {
            get {
                return ResourceManager.GetString("definition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap discard {
            get {
                object obj = ResourceManager.GetObject("discard", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap front {
            get {
                object obj = ResourceManager.GetObject("front", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap hand {
            get {
                object obj = ResourceManager.GetObject("hand", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icon {
            get {
                object obj = ResourceManager.GetObject("icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;templates&gt;
        ///  &lt;blocks&gt;
        ///    &lt;block type=&quot;text&quot; id=&quot;name&quot;&gt;
        ///      &lt;location x=&quot;50&quot; y=&quot;50&quot;/&gt;
        ///      &lt;text color=&quot;#000000&quot; size=&quot;20&quot;/&gt;
        ///    &lt;/block&gt;
        ///    &lt;block type=&quot;text&quot; id=&quot;type&quot;&gt;
        ///      &lt;location x=&quot;50&quot; y=&quot;150&quot;/&gt;
        ///      &lt;text color=&quot;#000000&quot; size=&quot;20&quot;/&gt;
        ///    &lt;/block&gt;
        ///  &lt;/blocks&gt;
        ///  &lt;template src=&quot;Resources/blank.png&quot; default=&quot;True&quot;&gt;
        ///    &lt;matches&gt;
        ///      &lt;match name=&quot;property&quot; value=&quot;name&quot; /&gt;
        ///    &lt;/matches&gt;
        ///    &lt;textblocks&gt;
        ///      &lt;link block=&quot;name&quot;&gt;
        ///        &lt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string proxydef {
            get {
                return ResourceManager.GetString("proxydef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap score {
            get {
                object obj = ResourceManager.GetObject("score", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;set name=&quot;Base Set&quot; id=&quot;071443fe-b5d1-43b4-bb3a-284c4f6d52ce&quot; gameId=&quot;263b2f19-fb22-4f32-82dd-3d1b28d3da3a&quot; gameVersion=&quot;1.0.0.0&quot; version=&quot;1.0&quot;&gt;
        ///    &lt;cards&gt;
        ///        &lt;card id=&quot;4decba1c-41fa-4dea-85d6-18f8906af845&quot; name=&quot;Ace of Spades&quot;&gt;
        ///            &lt;property name=&quot;Rules&quot; value=&quot;Play this card whenever!&quot; /&gt;
        ///            &lt;property name=&quot;Type&quot; value=&quot;Black Card&quot; /&gt;
        ///          &lt;alternate name=&quot;Alternate Card&quot; type=&quot;altA&quot;&gt;
        ///            &lt;property name=&quot;Ru [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string set {
            get {
                return ResourceManager.GetString("set", resourceCulture);
            }
        }
    }
}
